### ISSUE TITLE
Concistency in parameter naming

### ISSUE THREAD

**Issue by hallegue** [squid-group/squidSim#14]
Here some thoughts on naming parameters:

The population id in the output dataset is named `squid_pop`. None of the other parameters is preceded by `squid_`. May be have it just `pop` or `population`.

All parameter names are in lower case except `N` and `N_pop`. What about `n` and `n_pop`?

**Comment by joelpick** [comment]
So the thought process here was that population or pop seems like it would be a common group name in simulations - like if you were simulating data from multiple populations, population or some variant would be in your data structure. Making it a reserved name would then be pretty annoying for a user. The aim was therefore to name it something that was very unlikely to be part of someone’s data structure.

All other variables are named by the user (or made from user provided names. The idea of proceeding it with squid was deliberately to distinguish it from the users data structure, so I don’t think it is a consistency issue. There are likely plenty of better names though :) 

Alternatively we can just return it as a list, rather than a giant data frame. Personally I don’t see in what scenario the giant data frame would be used over the list. The ‘squid_pop’ naming is only useful in the data frame output

**Comment by joelpick** [comment]
in regard to `n` versus `N` - I think its gone back and forth - I think I thought `N` seemed more appropriate somehow, but hadn't thought about the consistency in the capitalisation. I'm easy either way

**Comment by hallegue** [comment]
Ok, I didn't think about the variable names defined by the user.
